package ui.dialog;

import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Yumi Takuma
 */
public class AddClient extends javax.swing.JDialog {

    /**
     * Creates new form AddClient
     */
    public AddClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        SwingUtilities.updateComponentTreeUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addClientPanel = new javax.swing.JPanel();
        changeBtn = new javax.swing.JButton();
        miLbl = new javax.swing.JLabel();
        fnLbl = new javax.swing.JLabel();
        lnLbl = new javax.swing.JLabel();
        gLbl = new javax.swing.JLabel();
        bdayLbl = new javax.swing.JLabel();
        addLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        mobileLbl = new javax.swing.JLabel();
        eaddLbl = new javax.swing.JLabel();
        miTF = new javax.swing.JTextField();
        fnTF = new javax.swing.JTextField();
        lnTF = new javax.swing.JTextField();
        gCB = new javax.swing.JComboBox();
        mBdayLbl = new javax.swing.JComboBox();
        dBdaySpinner = new javax.swing.JSpinner();
        yBdaySpinner = new javax.swing.JSpinner();
        addTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        mobileTF = new javax.swing.JTextField();
        eaddTF = new javax.swing.JTextField();
        doneBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Client");

        addClientPanel.setBackground(new java.awt.Color(255, 255, 255));
        addClientPanel.setForeground(new java.awt.Color(255, 255, 255));

        changeBtn.setBackground(new java.awt.Color(255, 255, 255));
        changeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changeBtn.setText("CHANGE PHOTO");

        miLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        miLbl.setText("M.I:");

        fnLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        fnLbl.setText("FIRST NAME:");

        lnLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lnLbl.setText("LAST NAME:");

        gLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        gLbl.setText("GENDER:");

        bdayLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        bdayLbl.setText("BIRTHDAY:");

        addLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        addLbl.setText("ADDRESS:");

        phoneLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        phoneLbl.setText("PHONE:");

        mobileLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        mobileLbl.setText("MOBILE:");

        eaddLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        eaddLbl.setText("E-ADD:");

        miTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        fnTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lnTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        gCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        gCB.setToolTipText("");

        mBdayLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mBdayLbl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        dBdaySpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dBdaySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        yBdaySpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yBdaySpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997"}));

        addTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        phoneTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mobileTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        eaddTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        doneBtn.setBackground(new java.awt.Color(255, 255, 255));
        doneBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        doneBtn.setText("DONE");

        cancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        cancelBtn.setText("Cancel");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/buttons/camera.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout addClientPanelLayout = new javax.swing.GroupLayout(addClientPanel);
        addClientPanel.setLayout(addClientPanelLayout);
        addClientPanelLayout.setHorizontalGroup(
            addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClientPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClientPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addClientPanelLayout.createSequentialGroup()
                            .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addLbl)
                                .addComponent(fnLbl)
                                .addComponent(gLbl)
                                .addComponent(phoneLbl)
                                .addComponent(eaddLbl))
                            .addGap(18, 18, 18)
                            .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(addClientPanelLayout.createSequentialGroup()
                                        .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(gCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lnLbl)
                                            .addComponent(bdayLbl))
                                        .addGap(18, 18, 18)
                                        .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(addClientPanelLayout.createSequentialGroup()
                                                .addComponent(lnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(miLbl)
                                                .addGap(18, 18, 18)
                                                .addComponent(miTF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(addClientPanelLayout.createSequentialGroup()
                                                .addComponent(mBdayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dBdaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(yBdaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(addTF)
                                    .addGroup(addClientPanelLayout.createSequentialGroup()
                                        .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mobileLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(mobileTF, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(eaddTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(addClientPanelLayout.createSequentialGroup()
                            .addGap(217, 217, 217)
                            .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        addClientPanelLayout.setVerticalGroup(
            addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClientPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClientPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClientPanelLayout.createSequentialGroup()
                        .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miLbl)
                    .addComponent(lnLbl)
                    .addComponent(fnLbl))
                .addGap(18, 18, 18)
                .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mBdayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dBdaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yBdaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdayLbl)
                    .addComponent(gLbl))
                .addGap(18, 18, 18)
                .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLbl))
                .addGap(18, 18, 18)
                .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLbl)
                    .addComponent(mobileLbl)
                    .addComponent(mobileTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eaddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eaddLbl))
                .addGap(28, 28, 28)
                .addGroup(addClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addClientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addClientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addClientPanel;
    private javax.swing.JLabel addLbl;
    private javax.swing.JTextField addTF;
    private javax.swing.JLabel bdayLbl;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton changeBtn;
    private javax.swing.JSpinner dBdaySpinner;
    private javax.swing.JButton doneBtn;
    private javax.swing.JLabel eaddLbl;
    private javax.swing.JTextField eaddTF;
    private javax.swing.JLabel fnLbl;
    private javax.swing.JTextField fnTF;
    private javax.swing.JComboBox gCB;
    private javax.swing.JLabel gLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lnLbl;
    private javax.swing.JTextField lnTF;
    private javax.swing.JComboBox mBdayLbl;
    private javax.swing.JLabel miLbl;
    private javax.swing.JTextField miTF;
    private javax.swing.JLabel mobileLbl;
    private javax.swing.JTextField mobileTF;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JSpinner yBdaySpinner;
    // End of variables declaration//GEN-END:variables
}
