package ui.dialog;

import javax.swing.SwingUtilities;

/**
 *
 * @author Yumi Takuma
 */
public class ViewEvent extends javax.swing.JDialog {

    /**
     * Creates new form ViewEvent
     */
    public ViewEvent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        SwingUtilities.updateComponentTreeUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewEventPanel = new javax.swing.JPanel();
        clientLbl = new javax.swing.JLabel();
        eventTypeLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        venueLbl = new javax.swing.JLabel();
        detailsLbl = new javax.swing.JLabel();
        expenseLbl = new javax.swing.JLabel();
        profitLbl = new javax.swing.JLabel();
        editBtn = new java.awt.Button();
        closeBtn = new java.awt.Button();
        deleteBtn = new java.awt.Button();
        monthCB = new javax.swing.JComboBox();
        clientTF = new javax.swing.JTextField();
        eventTypeCB = new javax.swing.JComboBox();
        daySpinner = new javax.swing.JSpinner();
        yearSpinner = new javax.swing.JSpinner();
        minStart = new javax.swing.JSpinner();
        hourStart = new javax.swing.JSpinner();
        sepStartLbl = new javax.swing.JLabel();
        toLbl = new javax.swing.JLabel();
        minEnd = new javax.swing.JSpinner();
        hourEnd = new javax.swing.JSpinner();
        sepEndLbl = new javax.swing.JLabel();
        venueTF = new javax.swing.JTextField();
        detailsSP = new javax.swing.JScrollPane();
        detailsTA = new javax.swing.JTextArea();
        expenseTF = new javax.swing.JTextField();
        profitTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Event");

        viewEventPanel.setBackground(new java.awt.Color(255, 255, 255));

        clientLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        clientLbl.setText("CLIENT:");

        eventTypeLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        eventTypeLbl.setText("EVENT TYPE:");

        dateLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        dateLbl.setText("DATE:");

        timeLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        timeLbl.setText("TIME:");

        venueLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        venueLbl.setText("VENUE:");

        detailsLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        detailsLbl.setText("DETAILS:");

        expenseLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        expenseLbl.setText("EXPENSE:");

        profitLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        profitLbl.setText("PROFIT:");

        editBtn.setActionCommand("EDIT");
        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        editBtn.setLabel("EDIT");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        closeBtn.setActionCommand("CLOSE");
        closeBtn.setBackground(new java.awt.Color(255, 255, 255));
        closeBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        closeBtn.setLabel("CLOSE");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        deleteBtn.setActionCommand("DELETE");
        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        deleteBtn.setLabel("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        monthCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        clientTF.setEditable(false);
        clientTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientTFActionPerformed(evt);
            }
        });

        eventTypeCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eventTypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anniversary", "Birthday", "Debut", "Graduation", "Wedding" }));

        daySpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        daySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        yearSpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yearSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036"}));

        minStart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        hourStart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sepStartLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sepStartLbl.setText(":");

        toLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toLbl.setText("to");

        minEnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        hourEnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sepEndLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sepEndLbl.setText(":");

        venueTF.setEditable(false);
        venueTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        detailsTA.setEditable(false);
        detailsTA.setColumns(20);
        detailsTA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        detailsTA.setRows(5);
        detailsSP.setViewportView(detailsTA);

        expenseTF.setEditable(false);
        expenseTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        profitTF.setEditable(false);
        profitTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout viewEventPanelLayout = new javax.swing.GroupLayout(viewEventPanel);
        viewEventPanel.setLayout(viewEventPanelLayout);
        viewEventPanelLayout.setHorizontalGroup(
            viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewEventPanelLayout.createSequentialGroup()
                .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewEventPanelLayout.createSequentialGroup()
                        .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewEventPanelLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(viewEventPanelLayout.createSequentialGroup()
                                        .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(clientLbl)
                                            .addComponent(dateLbl)
                                            .addComponent(timeLbl)
                                            .addComponent(venueLbl)
                                            .addComponent(detailsLbl))
                                        .addGap(7, 7, 7))
                                    .addComponent(profitLbl)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewEventPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eventTypeLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(expenseLbl, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(venueTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventTypeCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(viewEventPanelLayout.createSequentialGroup()
                                .addComponent(monthCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(daySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, viewEventPanelLayout.createSequentialGroup()
                                .addComponent(hourStart, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sepStartLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minStart, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(toLbl)
                                .addGap(18, 18, 18)
                                .addComponent(hourEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sepEndLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(detailsSP)
                            .addComponent(profitTF)
                            .addComponent(expenseTF)))
                    .addGroup(viewEventPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewEventPanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        viewEventPanelLayout.setVerticalGroup(
            viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewEventPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientLbl))
                .addGap(18, 18, 18)
                .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventTypeLbl))
                .addGap(18, 18, 18)
                .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLbl))
                .addGap(18, 18, 18)
                .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sepStartLbl)
                    .addComponent(toLbl)
                    .addComponent(minEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sepEndLbl)
                    .addComponent(timeLbl))
                .addGap(18, 18, 18)
                .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(venueLbl))
                .addGap(18, 18, 18)
                .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailsLbl)
                    .addGroup(viewEventPanelLayout.createSequentialGroup()
                        .addComponent(detailsSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expenseTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expenseLbl))
                        .addGap(18, 18, 18)
                        .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profitTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profitLbl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewEventPanelLayout.createSequentialGroup()
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(viewEventPanelLayout.createSequentialGroup()
                        .addGroup(viewEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewEventPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewEventPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void clientTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientTFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientLbl;
    private javax.swing.JTextField clientTF;
    private java.awt.Button closeBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JSpinner daySpinner;
    private java.awt.Button deleteBtn;
    private javax.swing.JLabel detailsLbl;
    private javax.swing.JScrollPane detailsSP;
    private javax.swing.JTextArea detailsTA;
    private java.awt.Button editBtn;
    private javax.swing.JComboBox eventTypeCB;
    private javax.swing.JLabel eventTypeLbl;
    private javax.swing.JLabel expenseLbl;
    private javax.swing.JTextField expenseTF;
    private javax.swing.JSpinner hourEnd;
    private javax.swing.JSpinner hourStart;
    private javax.swing.JSpinner minEnd;
    private javax.swing.JSpinner minStart;
    private javax.swing.JComboBox monthCB;
    private javax.swing.JLabel profitLbl;
    private javax.swing.JTextField profitTF;
    private javax.swing.JLabel sepEndLbl;
    private javax.swing.JLabel sepStartLbl;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JLabel toLbl;
    private javax.swing.JLabel venueLbl;
    private javax.swing.JTextField venueTF;
    private javax.swing.JPanel viewEventPanel;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables
}
