/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

/**
 *
 * @author Rei Ayame
 */
public class ViewClient extends javax.swing.JDialog {

    /**
     * Creates new form ViewClient
     */
    public ViewClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewClientPanel = new javax.swing.JPanel();
        imgLbl = new javax.swing.JLabel();
        changeBtn = new javax.swing.JButton();
        miLbl = new javax.swing.JLabel();
        fnLbl = new javax.swing.JLabel();
        lnLbl = new javax.swing.JLabel();
        gLbl = new javax.swing.JLabel();
        bdayLbl = new javax.swing.JLabel();
        addLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        mobileLbl = new javax.swing.JLabel();
        eaddLbl = new javax.swing.JLabel();
        miTF = new javax.swing.JTextField();
        fnTF = new javax.swing.JTextField();
        lnTF = new javax.swing.JTextField();
        gCB = new javax.swing.JComboBox();
        mBdayLbl = new javax.swing.JComboBox();
        dBdaySpinner = new javax.swing.JSpinner();
        yBdaySpinner = new javax.swing.JSpinner();
        addTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        mobileTF = new javax.swing.JTextField();
        eaddTF = new javax.swing.JTextField();
        doneBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Client");

        viewClientPanel.setBackground(new java.awt.Color(255, 255, 255));

        imgLbl.setBackground(new java.awt.Color(255, 255, 255));
        imgLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        imgLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        changeBtn.setBackground(new java.awt.Color(255, 255, 255));
        changeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changeBtn.setText("CHANGE PHOTO");

        miLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        miLbl.setText("M.I:");

        fnLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        fnLbl.setText("FIRST NAME:");

        lnLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lnLbl.setText("LAST NAME:");

        gLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        gLbl.setText("GENDER:");

        bdayLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        bdayLbl.setText("BIRTHDAY:");

        addLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        addLbl.setText("ADDRESS:");

        phoneLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        phoneLbl.setText("PHONE:");

        mobileLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        mobileLbl.setText("MOBILE:");

        eaddLbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        eaddLbl.setText("E-ADD:");

        miTF.setEditable(false);
        miTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        fnTF.setEditable(false);
        fnTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lnTF.setEditable(false);
        lnTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        gCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        gCB.setToolTipText("");

        mBdayLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mBdayLbl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        dBdaySpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dBdaySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        yBdaySpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yBdaySpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997"}));

        addTF.setEditable(false);
        addTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        phoneTF.setEditable(false);
        phoneTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mobileTF.setEditable(false);
        mobileTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        eaddTF.setEditable(false);
        eaddTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        doneBtn.setBackground(new java.awt.Color(255, 255, 255));
        doneBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        doneBtn.setText("DONE");

        cancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        cancelBtn.setText("Cancel");

        javax.swing.GroupLayout viewClientPanelLayout = new javax.swing.GroupLayout(viewClientPanel);
        viewClientPanel.setLayout(viewClientPanelLayout);
        viewClientPanelLayout.setHorizontalGroup(
            viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewClientPanelLayout.createSequentialGroup()
                .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewClientPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addLbl)
                            .addComponent(fnLbl)
                            .addComponent(gLbl)
                            .addComponent(phoneLbl)
                            .addComponent(eaddLbl))
                        .addGap(18, 18, 18)
                        .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(viewClientPanelLayout.createSequentialGroup()
                                    .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(gCB, 0, 150, Short.MAX_VALUE)
                                        .addComponent(fnTF))
                                    .addGap(18, 18, 18)
                                    .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lnLbl)
                                        .addComponent(bdayLbl))
                                    .addGap(18, 18, 18)
                                    .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(viewClientPanelLayout.createSequentialGroup()
                                            .addComponent(lnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(miLbl)
                                            .addGap(18, 18, 18)
                                            .addComponent(miTF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(viewClientPanelLayout.createSequentialGroup()
                                            .addComponent(mBdayLbl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dBdaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(yBdaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(addTF)
                                .addGroup(viewClientPanelLayout.createSequentialGroup()
                                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(mobileLbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(mobileTF)))
                            .addComponent(eaddTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(viewClientPanelLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewClientPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgLbl)
                .addGap(18, 18, 18)
                .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
        viewClientPanelLayout.setVerticalGroup(
            viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewClientPanelLayout.createSequentialGroup()
                .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewClientPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(imgLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewClientPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miLbl)
                    .addComponent(lnLbl)
                    .addComponent(fnLbl))
                .addGap(18, 18, 18)
                .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mBdayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dBdaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yBdaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdayLbl)
                    .addComponent(gLbl))
                .addGap(18, 18, 18)
                .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLbl))
                .addGap(18, 18, 18)
                .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLbl)
                    .addComponent(mobileLbl)
                    .addComponent(mobileTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eaddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eaddLbl))
                .addGap(28, 28, 28)
                .addGroup(viewClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewClientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewClientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewClient dialog = new ViewClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLbl;
    private javax.swing.JTextField addTF;
    private javax.swing.JLabel bdayLbl;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton changeBtn;
    private javax.swing.JSpinner dBdaySpinner;
    private javax.swing.JButton doneBtn;
    private javax.swing.JLabel eaddLbl;
    private javax.swing.JTextField eaddTF;
    private javax.swing.JLabel fnLbl;
    private javax.swing.JTextField fnTF;
    private javax.swing.JComboBox gCB;
    private javax.swing.JLabel gLbl;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JLabel lnLbl;
    private javax.swing.JTextField lnTF;
    private javax.swing.JComboBox mBdayLbl;
    private javax.swing.JLabel miLbl;
    private javax.swing.JTextField miTF;
    private javax.swing.JLabel mobileLbl;
    private javax.swing.JTextField mobileTF;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JPanel viewClientPanel;
    private javax.swing.JSpinner yBdaySpinner;
    // End of variables declaration//GEN-END:variables
}
